[env]
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'

[tools]
# Kubectl + Plugins
"aqua:kubectl" = "1.34.2"
"aqua:fluxcd/flux2" = "2.7.3"
"aqua:kustomize" = "latest"
"aqua:helm" = "latest"
"aqua:derailed/k9s" = "latest"
clusterctl = "latest"

# Talos Stuff
"aqua:talosctl" = "1.11.5"
"aqua:talhelper" = "3.0.39"

# Terraform Stuff
terragrunt = "latest"
opentofu = "1"
op = "latest"

# Ansible Stuff
"pipx:ansible-core" = "latest"

# Misc Tools
task = "3"
sops = "3"
age = "1"
direnv = "latest"

# Linters
yamlfmt = "latest"
actionlint = "latest"
shellcheck = "latest"
