apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    bar: ENC[AES256_GCM,data:GStP,iv:e9/OoGvw1oQA1F9in3NYu8MSBJ+o+U+j+31bDQFkvW0=,tag:p0pJWopAaK147FUkQ5vFBQ==,type:str]
sops:
    age:
        - recipient: age1d7fjm42t7d8r9g4glua85tkrf4txswk2hnc8s4pgr8nyupnenfhqmegklw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0enpYQU9DbjlJY080VjZu
            OVYvM2JBdndNUTd1WlNlbG82K2dUQmIrU3dnCkI3N2RTUWdHeXRNUXpPajhwUjBD
            MngyTUpwODlmTnM1YXBvWFlWTlpYTzgKLS0tIFVLazhGa1JDdVR2aU1hUEh2K2Jj
            UU44MW5nZExPL2c0aWZqN1J5MHZ2ZEEKRe2vLSh1SaZdk6qP87foODigNSXQujGy
            SCp+5agzkfRmWUs5e1t27znhhcZbtNZHEdjh1EwEqthdHib5K/j+QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T20:44:38Z"
    mac: ENC[AES256_GCM,data:aa4yOWP7ZWpjVPRdeMjoieaiR71++FJd1PSIy/n13sPK4CEPWTuWms3dvaAZuEjJAo42/nGw1w5EzoS1uUfYBHByD7aNZFuoPCFqXn02GUhvfACTD+HWw6r090brcNBBIpPyANs68lLtv3zam6MMIszLLZw5fssWruqZReMMaKI=,iv:19eO2c468/2xOYV7Iko5e+MplFGliQdj6/X5cG2XeJU=,tag:RFhkV5C/MKpn+bZB6P9pSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
