---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: flux-operator
spec:
  # Labels required on the target clusters to install this Helm chart
  clusterSelector:
    matchLabels:
      helm-apps.home.mirceanton.com/flux-bootstrap: "enabled"

  # Helm Install Options
  reconcileStrategy: Continuous
  options:
    install:
      createNamespace: true
    waitForJobs: true

  # Helm Release Info
  releaseName: flux-operator
  namespace: flux-system

  # Helm Chart Source
  repoURL: oci://ghcr.io/controlplaneio-fluxcd/charts/
  version: v0.33.0
  chartName: flux-operator

  valuesTemplate: ""
